# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuário')),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, db_column='RG', max_length=15, null=True, unique=True, verbose_name='RG')),
                ('matricula', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Matrícula')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Gênero')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('grupo_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Tipo de Usuário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'verbose_name': 'Usuário',
            },
        ),
        migrations.AddField(
            model_name='placacarro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
