# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placacarro',
            options={'verbose_name': 'Placa', 'verbose_name_plural': 'Placas'},
        ),
        migrations.AlterField(
            model_name='placacarro',
            name='numero',
            field=models.CharField(max_length=8, verbose_name='Ńúmero da Placa'),
        ),
        migrations.AlterField(
            model_name='placacarro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
