# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='grupo_usuario',
        ),
    ]
