# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20160723_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placacarro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
