# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20160603_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
