# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20160603_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=45),
        ),
    ]
