# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20160606_1815'),
        ('usuario', '0005_auto_20160606_2314'),
    ]

    operations = [
    ]
