# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_confirmaemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmaEmail',
        ),
    ]
