# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20160619_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, db_column='CPF', max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=45, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, db_column='RG', max_length=15, null=True, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Gênero'),
        ),
    ]
