# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unb_alerta.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome_cod', models.CharField(max_length=40, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Local')),
                ('pai', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locais',
                'verbose_name': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data da Ocorrência')),
                ('hora', models.TimeField()),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('informacoes_segurancas', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Informações dos Seguranças')),
                ('foto', models.ImageField(blank=True, max_length=45, null=True, upload_to='ocorrencia/%Y/%m/%d', validators=[unb_alerta.utils.restringe_tipos_de_arquivo_img])),
                ('validade', models.BooleanField()),
                ('atendida', models.BooleanField()),
                ('emergencia', models.BooleanField(verbose_name='Emergência')),
                ('vitimado', models.BooleanField()),
                ('repetida', models.BooleanField()),
                ('resposta', models.CharField(blank=True, max_length=500, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Local', verbose_name='Local')),
                ('tb_categoria_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Categoria', verbose_name='Categoria')),
                ('usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_usuario', to='usuario.Usuario')),
                ('vigilante_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_vigilante', to='usuario.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Ocorrências',
                'verbose_name': 'Ocorrência',
            },
        ),
    ]
