# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='informacoes_segurancas',
            field=models.TextField(blank=True, null=True, verbose_name='Informações dos Seguranças'),
        ),
    ]
