# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
