# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome_cod',
            field=models.CharField(max_length=40, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='emergencia',
            field=models.BooleanField(verbose_name='Emergência'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
