# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_auto_20160620_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='emergencia',
            field=models.BooleanField(verbose_name='Emergência'),
        ),
    ]
