# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_auto_20160526_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
