# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_auto_20160706_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Local'),
        ),
    ]
