# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_auto_20160706_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='resposta',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
