# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_auto_20160706_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOcorrencia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'verbose_name': 'Status',
            },
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='atendida',
            field=models.BooleanField(verbose_name='Foi atendida?'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='emergencia',
            field=models.BooleanField(verbose_name='Emergência?'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='hora',
            field=models.TimeField(verbose_name='Hora da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='repetida',
            field=models.BooleanField(verbose_name='É repetida?'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='usuario_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_usuario', to='usuario.Usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='validade',
            field=models.BooleanField(verbose_name='É válida?'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vigilante_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_vigilante', to='usuario.Usuario', verbose_name='Vigilante'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vitimado',
            field=models.BooleanField(verbose_name='Possui vítimas?'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.StatusOcorrencia', verbose_name='Status da Ocorrência'),
        ),
    ]
