# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_auto_20160621_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='resposta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
