# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_auto_20160723_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusocorrencia',
            old_name='tipo',
            new_name='status',
        ),
    ]
