# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0006_ocorrencia_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
